### PR TITLE
[add] Makilab #66

### PR DESCRIPTION
**Pull request by jonadem**
It was tested using a snippet ([source here](https://gist.github.com/jonadem/b5c72a919cb33801dd69f2d69d418fb9)) because I was not able to create an instance of the hackeragenda (I will create a bugreport for this ASAP).

### CODE REVIEW

**Comment by jonadem** [comment]
I had the same issue as the Travis CI (It was tested with Ubuntu 16.4 LTS and Debian 9).

**Comment by Psycojoker** [comment]
Hey :)

Finally took the time to merge that, sorry for the delay and I've also I've fixed the installation part.

Thanks for your contribution :heart:

**Comment by jonadem** [comment]
My pleasure !

Do you have an idea when Makilab will be found on hackeragenda.be ?

Thanks

**Comment by Psycojoker** [comment]
Should be good now :)

(deployment had changed and I updated the wrong location >.>)

**Pull request merged**
